version: '2'
services:
  dagster:
    build: .
    environment:
      - DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1
      - DAGSTER_HOME=/usr/app/respiratorios/dagster_home
      - DAGSTER_PATH_PREFIX=${DAGSTER_PATH_PREFIX}
    ports:
      - "3007:3000"
    volumes:
      - .:/usr/app/respiratorios/
    entrypoint: ["./entrypoint.sh"]
    networks:
      - respatnetwork
    mem_limit: "4g"
    mem_reservation: "1g"
    memswap_limit: "6g"    
  xlsx2csv:
    build: ./xlsx2csv_converter
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "2140"]
    networks:
      - respatnetwork

networks:
  respatnetwork:
    driver: bridge
