version: 2

models:
  - name: sivep_02_fix_values
    description: Convert data types and rename columns
    columns:
      - name: date_testing
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              name: sivep_02_future_date
              expression: "<= current_date"
      - name: sex
        tests:
          - not_null:
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">100"
          - accepted_values:
              values: ["M", "F"]
      - name: location
        tests:
          - not_null
      - name: state
        tests:
          - accepted_uf_names
          - not_null:
              name: sivep_02_state_not_null
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">100"
      - name: age
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 200
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">100"
          - not_null:
              name: sivep_02_age_not_null
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">100"
      - name: FLUA_antigen_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: FLUB_antigen_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: SC2_antigen_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: VSR_antigen_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: PARA_antigen_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: ADENO_antigen_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: FLUA_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: FLUB_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: SC2_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: VSR_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: ADENO_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: META_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: BOCA_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: RINO_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
      - name: PARA_pcr_result
        quote: true
        tests:
          - accepted_values:
              values: [0, 1]
